import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class ImageIcons {
  static const AssetImage home = AssetImage('assets/image/home.png');
  static const AssetImage moneyCollect = AssetImage('assets/image/money_collect.png');
  static const AssetImage message = AssetImage('assets/image/message.png');
  static const AssetImage search = AssetImage('assets/image/search.png');
  static const AssetImage user = AssetImage('assets/image/user.png');
  static const AssetImage vipBuy = AssetImage('assets/image/0d851513e1c83d0a6573777b07de830e-mine.png');
  static const AssetImage promote = AssetImage('assets/image/544291d4f6326541a03f3e9a71cd95b4-mine2.png');
  static const AssetImage income = AssetImage('assets/image/8e2307242822dac65070263b26fb6c0f-mine3.png');
  static const AssetImage zhipianrenjihua = AssetImage('assets/image/zhipianrenjihua.jpg');
  static const AssetImage tuku = AssetImage('assets/image/tuku.png');
  static const AssetImage nan = AssetImage('assets/image/nan.png');
  static const AssetImage nv = AssetImage('assets/image/nv.png');
  static const AssetImage sex = AssetImage('assets/image/sex.png');
  static const AssetImage age = AssetImage('assets/image/age.png');
  static const AssetImage yue = AssetImage('assets/image/yue.jpg');
  static const AssetImage alipay = AssetImage('assets/image/alipay.png');
  static const AssetImage wechat = AssetImage('assets/image/wechat.png');
  static const AssetImage button_y = AssetImage('assets/image/button_y.jpg');
  static const AssetImage yingyongzhongxin = AssetImage('assets/image/yingyongzhongxin.png');
  static const AssetImage wodeshoucang = AssetImage('assets/image/wodeshoucang.png');
  static const AssetImage kaichejinqun = AssetImage('assets/image/kaichejinqun.png');
  static const AssetImage guankanjilu = AssetImage('assets/image/guankanjilu.png');
  static const AssetImage goumaizuanshi = AssetImage('assets/image/goumaizuanshi.png');
  static const AssetImage goumaijinbi = AssetImage('assets/image/goumaijinbi.png');
  static const AssetImage bangzhufankui = AssetImage('assets/image/bangzhufankui.png');
  static const AssetImage wode = AssetImage('assets/image/wode.png');
  static const AssetImage bgBuyDinmond = AssetImage('assets/image/bgBuyDinmond.png');
  static const AssetImage GoldCoins = AssetImage('assets/image/GoldCoins.png');
  static const AssetImage reason = AssetImage('assets/image/reason.png');
  static const AssetImage top1Bg = AssetImage('assets/image/top1Bg.png');
  static const AssetImage share = AssetImage('assets/image/share.png');
  static const AssetImage star = AssetImage('assets/image/star.png');
  static const AssetImage star_half = AssetImage('assets/image/star-half.png');
  static const AssetImage nomalBg = AssetImage('assets/image/nomalBg.png');
  static const AssetImage diamond = AssetImage('assets/image/diamond.png');
  static const AssetImage remommendIcon = AssetImage('assets/image/remommendIcon.png');
  static const AssetImage actorIcon = AssetImage('assets/image/fa4b534d-a31f-48b9-b425-4363f244d402.png');
  static const AssetImage icon_share = AssetImage('assets/image/icon_share.png');
  static const AssetImage icon_download = AssetImage('assets/image/icon_download.png');
  static const AssetImage zanIcon = AssetImage('assets/image/zanIcon.png');
  static const AssetImage like = AssetImage('assets/image/like.png');
}